name: main

on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - run: bun install --frozen-lockfile

      - run: bun type
      - run: bun lint
      - run: bun test
      - run: bunx vite build --base yAR-htzee
        env:
          VITE_XR8_API_KEY: ${{ secrets.VITE_XR8_API_KEY }}
      - run: cp doc/* ./dist/
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist
      - uses: actions/deploy-pages@v4
        if: success() && github.ref == 'refs/heads/master'
